In [248]:
import numpy as np

In [249]:
a = np.array([
    [0.053, 0.020, 0.010, 0.0, 0.0],
    [0.030, 0.050, 0.030, 0.050, 0.012],
    [0.0, 0.020, 0.200, 0.040, 0.0],
    [0.060, 0.070, 0.030, 0.0, 0.0],
    [0.020, 0.005, 0.049, 0.02, 0.0],
    [0.025, 0.045, 0.0175, 0.0, 0.0]
])
a.shape

(6, 5)

In [250]:
y = np.array([18, 17, 18, 0.1, 0.5])
# 18, 17, 18, 0.1, 30
y.shape


(5,)

In [251]:
def unit_vector(v):
    return v / np.linalg.norm(v, ord=2)

In [252]:

a_units = np.array([unit_vector(ai) for ai in a])
a_units


array([[0.92135604, 0.34768152, 0.17384076, 0.        , 0.        ],
       [0.36001152, 0.6000192 , 0.36001152, 0.6000192 , 0.14400461],
       [0.        , 0.09759001, 0.97590007, 0.19518001, 0.        ],
       [0.61885275, 0.72199487, 0.30942637, 0.        , 0.        ],
       [0.35212577, 0.08803144, 0.86270815, 0.35212577, 0.        ],
       [0.45980049, 0.82764088, 0.32186034, 0.        , 0.        ]])

In [253]:
y_unit = unit_vector(y)
y_unit

array([0.5879528 , 0.55528876, 0.5879528 , 0.0032664 , 0.01633202])

In [254]:

p = np.array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5])
a_units_t = a_units.T
a_units_dot_y_unit = np.dot(y_unit, a_units.T)

def check_neighbor(i, p_diff):
    tmp_p = p.copy()
    tmp_p[i] += p_diff
    unit_p = tmp_p / sum(tmp_p)
    cos_similarity = np.dot(a_units_dot_y_unit, unit_p)
    
    return cos_similarity

for i, pi in enumerate(p):
    prev_cos_similarity = check_neighbor(i, 0.0)
    p_diff = 0.5
    
    for _ in range(100):
        if check_neighbor(i, 0.5 * p_diff) > prev_cos_similarity:
            p[i] += p_diff
        elif check_neighbor(i, -0.5 * p_diff) > prev_cos_similarity:
            p[i] -= p_diff
            
        p_diff *= 0.5
        prev_cos_similarity = check_neighbor(i, p_diff)
    
    print(check_neighbor(0, 0))

v = np.dot(a.T, p)
ratio = y[0] / v[0]
v *= ratio
v

0.8133684736242255
0.8133684736242257
0.8133684736242259
0.8300349074997025
0.8300349074997029
0.8399376235775594


array([18.        , 19.04907975, 21.75460123,  6.07361963,  0.66257669])

In [255]:
y

array([18. , 17. , 18. ,  0.1,  0.5])

In [256]:
p * ratio

array([110.42944785,  55.21472393,  55.21472393, 110.42944785,
        55.21472393, 110.42944785])